// 高峰競賽平台 Firestore 安全同步服務 V2.2.3
(function(){
  'use strict';
  const MAP={users:'people',products:'products',rates:'exchangeRates',competitions:'competitions',bonus:'rewardActivities',sales:'sales',history:'archives',audit:'auditLogs'};
  let ready=false,lastError='',baseUrl='',commitUrl='',projectId='',apiKey='';
  const clean=v=>JSON.parse(JSON.stringify(v,(_k,x)=>x===undefined?null:x));
  const enc=v=>v==null?{nullValue:null}:typeof v==='boolean'?{booleanValue:v}:typeof v==='number'?(Number.isInteger(v)?{integerValue:String(v)}:{doubleValue:v}):typeof v==='string'?{stringValue:v}:Array.isArray(v)?{arrayValue:{values:v.map(enc)}}:{mapValue:{fields:encFields(v)}};
  const encFields=o=>Object.fromEntries(Object.entries(clean(o||{})).map(([k,v])=>[k,enc(v)]));
  const dec=v=>!v||'nullValue'in v?null:'booleanValue'in v?v.booleanValue:'integerValue'in v?Number(v.integerValue):'doubleValue'in v?Number(v.doubleValue):'stringValue'in v?v.stringValue:'timestampValue'in v?v.timestampValue:'arrayValue'in v?(v.arrayValue.values||[]).map(dec):'mapValue'in v?decFields(v.mapValue.fields||{}):null;
  const decFields=f=>Object.fromEntries(Object.entries(f||{}).map(([k,v])=>[k,dec(v)]));
  const status=(s,m='')=>window.dispatchEvent(new CustomEvent('peak:firebase-status',{detail:{status:s,message:m}}));
  async function req(url,opt={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(url,{...opt,signal:c.signal,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const txt=await r.text();let data=null;try{data=txt?JSON.parse(txt):null}catch{}if(!r.ok){const e=new Error(data?.error?.message||`${r.status} ${r.statusText}`);e.code=data?.error?.status||`http-${r.status}`;throw e}return data}finally{clearTimeout(t)}}
  async function init(force=false){if(ready&&!force)return true;status('checking','正在檢查雲端');const c=window.firebaseConfig||{};projectId=String(c.projectId||'').trim();apiKey=String(c.apiKey||'').trim();if(!projectId||!apiKey){lastError='Firebase 設定不完整';status('error',lastError);return false}baseUrl=`https://firestore.googleapis.com/v1/projects/${encodeURIComponent(projectId)}/databases/(default)/documents`;commitUrl=`https://firestore.googleapis.com/v1/projects/${encodeURIComponent(projectId)}/databases/(default)/documents:commit?key=${encodeURIComponent(apiKey)}`;try{await req(`${baseUrl}/settings/main?key=${encodeURIComponent(apiKey)}`).catch(e=>{if(!['NOT_FOUND','http-404'].includes(e.code))throw e});ready=true;lastError='';status('connected',`已連線 ${projectId}`);return true}catch(e){ready=false;lastError=`${e.code||'error'}：${e.message}`;status('error',lastError);return false}}
  const docName=(col,id)=>`projects/${projectId}/databases/(default)/documents/${col}/${id}`;
  async function commit(writes){for(let i=0;i<writes.length;i+=300)await req(commitUrl,{method:'POST',body:JSON.stringify({writes:writes.slice(i,i+300)})})}
  async function list(col){const rows=[];let token='';do{const q=new URLSearchParams({pageSize:'1000',key:apiKey});if(token)q.set('pageToken',token);const d=await req(`${baseUrl}/${encodeURIComponent(col)}?${q}`);(d.documents||[]).forEach(x=>{const id=decodeURIComponent(x.name.split('/').pop());if(id!=='_meta')rows.push({id,...decFields(x.fields||{})})});token=d.nextPageToken||''}while(token);return rows}
  async function getSettings(){try{const d=await req(`${baseUrl}/settings/main?key=${encodeURIComponent(apiKey)}`);return decFields(d.fields||{})}catch(e){if(['NOT_FOUND','http-404'].includes(e.code))return null;throw e}}
  async function syncCollection(col,rows){const normalized=(rows||[]).map((r,i)=>({...clean(r),id:String(r.id||`${Date.now()}-${i}`)}));const current=await list(col);const ids=new Set(normalized.map(r=>r.id));const writes=normalized.map(r=>({update:{name:docName(col,r.id),fields:encFields(r)}}));current.forEach(r=>{if(!ids.has(r.id))writes.push({delete:docName(col,r.id)})});if(!normalized.length)writes.push({update:{name:docName(col,'_meta'),fields:encFields({placeholder:true,updatedAt:new Date().toISOString()})}});if(writes.length)await commit(writes)}
  async function upload(state){if(!await init())throw new Error(lastError);status('syncing','正在上傳本機資料');await commit([{update:{name:docName('settings','main'),fields:encFields({...clean(state.settings||{}),updatedAt:new Date().toISOString(),appVersion:'2.2.3'})}}]);for(const [key,col] of Object.entries(MAP)){status('syncing',`正在同步 ${col}`);await syncCollection(col,state[key]||[])}localStorage.setItem('peakCloudEnabled','1');status('synced','已同步至 Firebase');return true}
  async function download(){if(!await init())throw new Error(lastError);status('syncing','正在讀取雲端資料');const settings=await getSettings();const result={settings:settings||{}};for(const [key,col] of Object.entries(MAP))result[key]=await list(col);const has=!!settings||Object.keys(MAP).some(k=>Array.isArray(result[k])&&result[k].length>0);status('synced',has?'已載入雲端資料':'雲端目前沒有資料');return has?result:null}
  window.PeakFirebaseService={init,upload,download,isReady:()=>ready,getLastError:()=>lastError};
})();
